#!/usr/bin/perl

$maxdate = 0;
$mindate = 0x7fffffff;

$minlat = 180;
$minlon = 180;
$maxlat = -180;
$maxlon = -180;

$file = $ARGV[0];
die if ($file eq "");

mkdir "$file.out";


open(IN, "$file.snap");
while (<IN>) {
	if (/ 32:(\d+)/) {
		if ($1 > $maxdate) {
			$maxdate = $1;
		}
		if ($1 < $mindate) {
			$mindate = $1;
		}
	}

	@points = split(/ /);
	($lat, $lon) = split(/,/, $points[0]);

	if ($lat < $minlat) {
		$minlat = $lat;
	}
	if ($lon < $minlon) {
		$minlon = $lon;
	}
	if ($lat > $maxlat) {
		$maxlat = $lat;
	}
	if ($lon > $maxlon) {
		$maxlon = $lon;
	}

	push @lat, $lat;
	push @lon, $lon;
}

@lat = sort { $a <=> $b } @lat;
@lon = sort { $a <=> $b } @lon;

$minlat = $lat[$#lat * .10];
$maxlat = $lat[$#lat * .90];
$minlon = $lon[$#lon * .10];
$maxlon = $lon[$#lon * .90];

print "$mindate $maxdate\n";
print "$minlat,$minlon $maxlat,$maxlon\n";

$n = 0;
$interval = ($maxdate - $mindate) / 100;
for ($date = $mindate; $date < $maxdate + 10 * $interval; $date += $interval) {
	print "$date\n";
	$outfile = sprintf("%s.out/%05d", $file, $n++);

	system "/data2/data/github/datamaps/render -A -xl$date -- $file.dm 12 $minlat $minlon $maxlat $maxlon | /data2/data/github/pngquant/pngquant 256 | pngtopnm | ppmtogif > $outfile.gif";
}

system "gifsicle -O3 -lforever --colors 8 $file.out/*.gif > $file.gif";
